language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: pypy
    - python: pypy3
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 2.7

sudo: false

install:
 - pip install coverage

script:
 - coverage run --source=meow ./test_meow.py -v
 - coverage run --append --source=no ./test_no.py -v
 - coverage run --append --source=icebox ./test_icebox.py -v

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pycodestyle pyflakes
 - pycodestyle --statistics --count *.py
 - pyflakes *.py | tee >(wc -l)
