language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: pypy
    - python: pypy3
    - python: 3.8
    - python: 3.7

install:
 - pip install coverage

script:
 - coverage run --source=woof ./test_woof.py -v

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pycodestyle pyflakes
 - pycodestyle --statistics --count *.py
 - pyflakes *.py | tee >(wc -l)
